In [1]:
import pandas as pd

url = "https://learn.walsoftcomputers.com/csv/bi.csv"

df = pd.read_csv(url, encoding="ISO-8859-1")

df.head()

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [2]:
df.shape

(77, 11)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fNAME          77 non-null     object
 1   lNAME          77 non-null     object
 2   Age            77 non-null     int64
 3   gender         77 non-null     object
 4   country        77 non-null     object
 5   residence      77 non-null     object
 6   entryEXAM      77 non-null     int64
 7   prevEducation  77 non-null     object
 8   studyHOURS     77 non-null     int64
 9   Python         75 non-null     float64
 10  DB             77 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB

In [4]:
import pandas as pd

url = "https://learn.walsoftcomputers.com/csv/bi.csv"

df = pd.read_csv(url, encoding="ISO-8859-1")

df.head()

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [5]:
df.isnull().sum()

fNAME            0
lNAME            0
Age              0
gender           0
country          0
residence        0
entryEXAM        0
prevEducation    0
studyHOURS       0
Python           2
DB               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['gender'].value_counts()

gender
Female    41
Male      32
M          1
F          1
female     1
male       1
Name: count, dtype: int64

In [8]:

df['country'].value_counts()

country
Norway          47
Uganda           4
Kenya            3
Germany          3
Italy            2
Spain            2
Netherlands      2
Denmark          2
UK               2
Somali           2
Nigeria          2
France           2
norway           1
Norge            1
South Africa     1
Rsa              1
Name: count, dtype: int64

In [9]:
df['residence'].value_counts()

residence
Private         33
BI Residence    29
Sognsvann       12
BI-Residence     1
BIResidence      1
BI_Residence     1
Name: count, dtype: int64

In [10]:
df['prevEducation'].value_counts()

prevEducation
Bachelors       24
High School     18
Masters         16
Diploma          9
Doctorate        5
HighSchool       1
Barrrchelors     1
diploma          1
DIPLOMA          1
Diplomaaa        1
Name: count, dtype: int64

In [11]:
df.describe()

             Age  entryEXAM  studyHOURS     Python          DB
count  77.000000  77.000000   77.000000  75.000000   77.000000
mean   35.207792  76.753247  149.714286  75.853333   69.467532
std    10.341966  16.475784   12.743272  15.410328   17.033701
min    21.000000  28.000000  114.000000  15.000000   30.000000
25%    27.000000  69.000000  144.000000  71.000000   56.000000
50%    33.000000  80.000000  156.000000  81.000000   71.000000
75%    42.000000  90.000000  158.000000  85.000000   83.000000
max    71.000000  98.000000  160.000000  91.000000  100.000000

In [12]:
Q1 = df[['Age', 'entryEXAM', 'studyHOURS', 'Python', 'DB']].quantile(0.25)
Q3 = df[['Age', 'entryEXAM', 'studyHOURS', 'Python', 'DB']].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bounds:")
print(lower_bound)

print("\nUpper bounds:")
print(upper_bound)

Lower bounds:
Age             4.5
entryEXAM      37.5
studyHOURS    123.0
Python         50.0
DB             15.5
dtype: float64

Upper bounds:
Age            64.5
entryEXAM     121.5
studyHOURS    179.0
Python        106.0
DB            123.5
dtype: float64

In [13]:
numeric_cols = ['Age', 'entryEXAM', 'studyHOURS', 'Python', 'DB']

outlier_mask = (
    (df[numeric_cols] < lower_bound) |
    (df[numeric_cols] > upper_bound)
).any(axis=1)

df[outlier_mask]

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80
20,Prof,Birkeland,22,Male,Norway,BI Residence,45,High School,116,33.0,30
21,Hanna,Isaksen,24,Female,Norway,BI Residence,50,High School,114,30.0,50
32,Perry,Rønning,71,Female,Norway,Private,30,Doctorate,120,31.0,42
48,Jenny,Kristoffersen,26,Female,Norway,BI Residence,68,High School,124,48.0,62
49,Thea,Knutsen,28,Male,Norway,BI Residence,69,High School,120,45.0,70
53,Chinedu,Morison,36,Male,Nigeria,Private,28,Diploma,120,15.0,67
55,Chinedu,Okafor,69,Male,Nigeria,Private,94,Doctorate,160,87.0,88
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [14]:
df[df['Python'].isnull()]

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
33,Frank,Abrahamsen,23,Male,Norway,BI Residence,68,High School,152,NaN,70

In [15]:
df['Python'] = df['Python'].fillna(df['Python'].median())

In [16]:
df['Python'].isnull().sum()

np.int64(0)

In [17]:
df['gender'] = df['gender'].replace({
    'F': 'Female',
    'female': 'Female',
    'M': 'Male',
    'male': 'Male'
})

In [18]:
df['gender'].value_counts()

gender
Female    43
Male      34
Name: count, dtype: int64

In [19]:
df['country']=df['country'].replace({
    'norway':'Norway',
    'Norge':'Norway',
    'Rsa':'South Africa',
    'UK':'United Kingdo'
})

In [20]:
df['country'].value_counts()

country
Norway           49
Uganda            4
Kenya             3
Germany           3
South Africa      2
Denmark           2
Netherlands       2
Spain             2
Italy             2
United Kingdo     2
Somali            2
Nigeria           2
France            2
Name: count, dtype: int64

In [21]:
df[df['country']=='Somali']

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
51,Mwanaidi,Ali,32,Female,Somali,BI Residence,82,Bachelors,156,84.0,59
76,Mohammed,Salim,31,Male,Somali,Sognsvann,35,Masters,144,72.0,90

In [22]:
df['country']=df['country'].replace({
    'Somali':'Somalia'
})

In [23]:
df['country'].value_counts()

country
Norway           49
Uganda            4
Kenya             3
Germany           3
South Africa      2
Denmark           2
Netherlands       2
Spain             2
Italy             2
United Kingdo     2
Somalia           2
Nigeria           2
France            2
Name: count, dtype: int64

In [24]:
df['residence']=df['residence'].replace({
    'BI-Residence':'BI Residence',
    'BIResidence':'BI Residence',
    'BI_Residence':'BI Residence'
})

In [25]:
df['residence'].value_counts()

residence
Private         33
BI Residence    32
Sognsvann       12
Name: count, dtype: int64

In [26]:
df['prevEducation'] = df['prevEducation'].replace({
    'HighSchool': 'High School',
    'Barrrchelors': 'Bachelors',
    'diploma': 'Diploma',
    'DIPLOMA': 'Diploma',
    'Diplomaaa': 'Diploma'
})

In [27]:
df['prevEducation'].value_counts()

prevEducation
Bachelors      25
High School    19
Masters        16
Diploma        12
Doctorate       5
Name: count, dtype: int64

In [28]:
df['Python']=df['Python'].astype(int)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fNAME          77 non-null     object
 1   lNAME          77 non-null     object
 2   Age            77 non-null     int64
 3   gender         77 non-null     object
 4   country        77 non-null     object
 5   residence      77 non-null     object
 6   entryEXAM      77 non-null     int64
 7   prevEducation  77 non-null     object
 8   studyHOURS     77 non-null     int64
 9   Python         77 non-null     int64
 10  DB             77 non-null     int64
dtypes: int64(5), object(6)
memory usage: 6.7+ KB

In [30]:
print("FINAL DATA QUALITY REPORT")
print("--------------------------")

print("Rows:",df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

FINAL DATA QUALITY REPORT
--------------------------
Rows: 77
Columns: 11
Missing values: 0
Duplicate rows: 0

Data types:
fNAME            object
lNAME            object
Age               int64
gender           object
country          object
residence        object
entryEXAM         int64
prevEducation    object
studyHOURS        int64
Python            int64
DB                int64
dtype: object

In [31]:
print("Gender:")
print(df['gender'].value_counts())

print("\nCountry:")
print(df['country'].value_counts())

print("\nResidence:")
print(df['residence'].value_counts())

print("\nPrevious Education:")
print(df['prevEducation'].value_counts())

Gender:
gender
Female    43
Male      34
Name: count, dtype: int64

Country:
country
Norway           49
Uganda            4
Kenya             3
Germany           3
South Africa      2
Denmark           2
Netherlands       2
Spain             2
Italy             2
United Kingdo     2
Somalia           2
Nigeria           2
France            2
Name: count, dtype: int64

Residence:
residence
Private         33
BI Residence    32
Sognsvann       12
Name: count, dtype: int64

Previous Education:
prevEducation
Bachelors      25
High School    19
Masters        16
Diploma        12
Doctorate       5
Name: count, dtype: int64

In [32]:
df.loc[df['country'].str.contains('United King', na=False), 'country']

41    United Kingdo
74    United Kingdo
Name: country, dtype: object

In [33]:
df['country'] = df['country'].replace({
    'United Kingdo': 'United Kingdom'
})

In [34]:
df[df['country'].str.contains('United King', na=False)]

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
41,Emily,Thompson,39,Female,United Kingdom,Private,90,Masters,158,85,74
74,Sophie,Brown,33,Female,United Kingdom,Sognsvann,96,Masters,158,85,90

### Validation Correction

During validation, the value `United Kingdo` was identified as a truncated country name. It was corrected to `United Kingdom` to ensure consistent country naming.

In [35]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Rows:", len(df))
print("Columns:", len(df.columns))

Missing values: 0
Duplicate rows: 0
Rows: 77
Columns: 11

In [36]:
df.to_csv("Gousiya_Noorain_Task3_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [37]:
import os

print(os.path.exists("Gousiya_Noorain_Task3_cleaned.csv"))

True

## Data Cleaning Methodology

The dataset was inspected and cleaned to improve data quality, consistency, and reliability.

### Missing Values
- 2 missing values were found in the `Python` column.
- Missing values were replaced using the median Python score (81).

### Duplicate Records
- No duplicate rows were identified.
- Therefore, no rows were removed due to duplication.

### Inconsistent Values
Inconsistent categorical values were standardized, including:
- Gender variations → `Female` / `Male`
- Country variations → standardized country names
- Residence variations → `BI Residence`
- Education variations → standardized education categories

### Outlier Detection
The IQR method was used to identify potential numerical outliers. The flagged observations were retained because their values were plausible and there was no clear evidence of data-entry errors.

### Data Types
Numerical columns were verified and corrected where necessary. The `Python` column was converted from `float64` to `int64` after missing values were handled.

### Final Dataset
- **Rows:** 77
- **Columns:** 11
- **Missing values:** 0
- **Duplicate rows:** 0
- **Numerical columns:** 5
- **Categorical/Text columns:** 6

The cleaned dataset was saved as `Gousiya_Noorain_Task3_cleaned.csv`.

In [38]:
# Before vs After Data Quality Summary

summary = pd.DataFrame({
    'Metric': [
        'Rows',
        'Columns',
        'Missing Values',
        'Duplicate Rows',
        'Python Data Type'
    ],
    'Before': [
        77,
        11,
        2,
        0,
        'float64'
    ],
    'After': [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df['Python'].dtype
    ]
})

summary

             Metric   Before  After
0              Rows       77     77
1           Columns       11     11
2    Missing Values        2      0
3    Duplicate Rows        0      0
4  Python Data Type  float64  int64

In [39]:
# Preview of the cleaned dataset
df.head(10)

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59,55
1,Alex,Walekhwa,60,Male,Kenya,Private,79,Diploma,150,60,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,High School,130,74,50
3,Shoni,Hlongwane,22,Female,South Africa,Sognsvann,40,High School,120,81,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91,80
5,Hannah,Hansen,25,Female,Norway,BI Residence,66,High School,130,88,59
6,Ole,Johansen,27,Male,Norway,BI Residence,90,Bachelors,156,80,91
7,Lars,Olsen,29,Male,Norway,BI Residence,89,Bachelors,160,85,60
8,Bjørn,Larsen,31,Male,Norway,BI Residence,88,Bachelors,156,80,89
9,Sofie,Jensen,33,Female,Denmark,BI Residence,85,Bachelors,160,83,90

In [40]:
import os

os.path.exists("Gousiya_Noorain_Task3_cleaned.csv")

True

## Conclusion

The student dataset was successfully cleaned while preserving all valid records. Missing values were handled using median imputation, duplicate records were checked, inconsistent categorical values were standardized, potential outliers were evaluated using the IQR method, and data types were corrected.

The final dataset contains **77 rows and 11 columns**, with **0 missing values and 0 duplicate records**. The cleaned dataset is ready for further analysis and predictive modeling.